In [13]:
value = input("Enter the numbers with comma ")
list = value.split(",")
tuple = tuple(list)
print("list :",list)
print("tuple :", tuple)


TypeError: 'tuple' object is not callable

In [14]:
filename = input("Enter the filename :")
name = filename.split(".")
print("the extension is :", name[-1])

the extension is : py


In [23]:
color_list = ["Red","Green","White" ,"Black"]
print("the names are :", color_list[0],color_list[3])

the names are : Red Black


take input and show n+nn+nnn


In [34]:
a = int(input("Enter the number :"))
print(a+int(f'{a}{a}')+int(f'{a}{a}{a}'))



615


In [35]:
print(abs.__doc__)

Return the absolute value of the argument.


In [36]:
print("""
hello there
this is a multiline string
..........
heredoc string ----> finishes
""")


hello there
this is a multiline string
..........
heredoc string ----> finishes



In [37]:
r = int(input("Enter the value of radius :"))
pi = 3.1416
V = 4/3 * pi * r**3
print("the volume is :", V)


the volume is : 523.5999999999999


In [40]:
a = int(input("Enter a number"))
x = a - 17
if a > 17:
    print(x**2)

64


In [41]:
def difference(n):
    if n <= 17:
        return 17 - n
    else:
        return (n-17)**2
print(difference(24))
print(difference(12))

49
5


In [44]:
num = int(input("Enter the no :"))
if num in range(100,1000):
    print("yes, 1000")
elif num in range(100,2000):
    print("within 2000")
else:
    print("none")


within 2000


In [45]:
def rangE(n):
    return ((abs(1000 - n) <= 100) or (abs(2000 - n) <= 100))
print(rangE(500))

False


In [61]:
def sum_three(n1, n2, n3):
    sum = n1 + n2 + n3
    return sum
    if n1 == n2 == n3:
        sum = sum * 3
        return sum
print(sum_three(3,3,3))
print(sum_three(1,2,3))




9
6


In [56]:
def sum_thrice(x, y, z):

     sum = x + y + z
  
     if x == y == z:
      sum = sum * 3
     return sum

print(sum_thrice(1, 2, 3))
print(sum_thrice(3, 3, 3))

6
27


In [44]:
def new_str(str):
    if len(str) >= 2 and str[:2]== "Is":
        return str
    else:
        return "Is " + str
print(new_str("array"))
print(new_str("Isverygood"))

Is array
Isverygood


In [1]:
def copies(str,n):
    result = ""
    for i in range(n):
        result = result + str
    return result

print(copies("abc", 2))
print(copies(".java",3)) 
    

abcabc
.java.java.java


In [8]:
def larger_string(str, n):
	   result = ""
	   for i in range(n):
	      result = result + str
	   return result
	
print(larger_string('abc', 2))
print(larger_string('.py', 3))

abcabc
.py.py.py


In [3]:
class mynumbers():
    def __iter__(self):
        self.a = 1
        return self
    def __next__(self):
        x =self.a
        self.a += 1
        return x
myclass = mynumbers()
myiter = iter(myclass)
print(next(myiter))
print(next(myiter))

1
2


In [4]:
import datetime
x = datetime.datetime.now()
print(x)

2021-07-23 08:00:42.399097


In [9]:
import datetime
x = datetime.datetime.now()
print(x.year)
print(x.strftime("%A"))

2021
Friday


In [11]:
import datetime
x = datetime.datetime(1992, 7,28)
print(x)

1992-07-28 00:00:00


In [17]:
import datetime
x = datetime.datetime.now()
print(x.strftime('%a'))
print(x.strftime('%A'))
print(x.strftime('%b'))
print(x.strftime('%B'))
print(x.strftime('%d'))
print(x.strftime('%w'))

Fri
Friday
Jul
July
23
5


In [19]:
a = min(2,45,1)
b = max(52,48,72)
print(a)
print(b)

1
72


In [20]:
x = abs(-5.63)
print(x)

5.63


In [22]:
x = pow(12,3)
print(x)

1728


In [23]:
import math
x = math.sqrt(64)
print(x)

8.0


In [24]:
import math
x = math.ceil(1.3)
y = math.floor(1.3)
print(x)
print(y)

2
1


In [25]:
import math
x = math.pi
print(x)

3.141592653589793


In [32]:
import json
x = '{"name" : "john", "age" : 36,"city" :"LA"}'
y = json.loads(x)
print(y["city"])

LA


In [34]:
import json
x = {
    "name" : "jhon",
    "age" : 36,
    "city": "LA"
}
y = json.dumps(x)
print(y)

{"name": "jhon", "age": 36, "city": "LA"}


In [35]:
x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}
print(json.dumps(x))

{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cars": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.1}]}


In [40]:
x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}
print(json.dumps(x, indent=1))

{
 "name": "John",
 "age": 30,
 "married": true,
 "divorced": false,
 "children": [
  "Ann",
  "Billy"
 ],
 "pets": null,
 "cars": [
  {
   "model": "BMW 230",
   "mpg": 27.5
  },
  {
   "model": "Ford Edge",
   "mpg": 24.1
  }
 ]
}


In [42]:
x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}
print(json.dumps(x,indent=2,separators=(".","=")))

{
  "name"="John".
  "age"=30.
  "married"=true.
  "divorced"=false.
  "children"=[
    "Ann".
    "Billy"
  ].
  "pets"=null.
  "cars"=[
    {
      "model"="BMW 230".
      "mpg"=27.5
    }.
    {
      "model"="Ford Edge".
      "mpg"=24.1
    }
  ]
}


In [43]:
x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}
print(json.dumps(x, indent=2,separators=(",","="),sort_keys=True))

{
  "age"=30,
  "cars"=[
    {
      "model"="BMW 230",
      "mpg"=27.5
    },
    {
      "model"="Ford Edge",
      "mpg"=24.1
    }
  ],
  "children"=[
    "Ann",
    "Billy"
  ],
  "divorced"=false,
  "married"=true,
  "name"="John",
  "pets"=null
}


In [47]:
import re
txt = "The rain in spain"
x = re.search("^The.*spain$",txt)
if x:
    print("yes, hve a match")
else:
    print("nope")

yes, hve a match


In [ ]:
import re
txt = "She is a criminal"
x = re.search("^She.*criminal$",txt)
if x:
    print("Yes its a match")
else:
    print("nope")

In [2]:
import datetime
x = datetime.datetime.now()
print(x.strftime("%B"))

July


In [1]:
import datetime
u = datetime.datetime(1998,6,15)
print(u.strftime("%B"))

June


In [6]:
import re
txt = "heavy rain in spain"
x = re.search("^heavy.*spain$" , txt)
if x:
    print("yes....")
else:
    print("no")

yes....


In [7]:
import re
txt = "Talking to the moon"
x = re.findall("[a-s]" ,txt)
print(x)

['a', 'l', 'k', 'i', 'n', 'g', 'o', 'h', 'e', 'm', 'o', 'o', 'n']


In [9]:
import re
txt = "I have 56 dollars and 90 cents left"
x = re.findall('\d' ,txt)
print(x)


['5', '6', '9', '0']


In [10]:
import re
txt = "i owe him 95.30 cents"
x = re.findall('\d' ,txt)
print(x)

['9', '5', '3', '0']


In [11]:
import re
txt = "Spain is a beautiful country"
x = re.search("^Spain" ,txt)
if x:
    print("yes...")
else:
    print("No...")

yes...


In [15]:
import re
txt = "welcome to spain"
x = re.search("spain$" ,txt)
if x:
    print("yes")
else:
    print("no...")

yes


In [20]:
import re
txt = "rain in spain on plain"
x = re.findall("in*" ,txt)
print(x)
if x:
   print("yes")
else:
    print("no")


['in', 'in', 'in', 'in']
yes


In [22]:
import re
txt = "rain falls in spain"
x = re.findall("falls|stays" ,txt)
print(x)
if x:
    print("yes")
else:
    print("no")

['falls']
yes


In [25]:
import re
txt= "The rain of spain"
x = re.findall("\d" ,txt)
print(x)
if x:
    print("yes ")
else:
    print("no")

['T', 'h', 'e', ' ', 'r', 'a', 'i', 'n', ' ', 'o', 'f', ' ', 's', 'p', 'a', 'i', 'n']
yes 


In [26]:
import re
txt = "The rain in spain"
x = re.findall("\D",txt)
print(x)
if x:
    print("yes")
else:
    print("no")

['T', 'h', 'e', ' ', 'r', 'a', 'i', 'n', ' ', 'i', 'n', ' ', 's', 'p', 'a', 'i', 'n']
yes


In [3]:
file = open("demofile.txt", mode= "w")
file.write("Hello! welcome to the new file")
file.close()





In [5]:
file = open("demofile.txt", mode= "r")
#data = file.read()
#file.close()
#data
print(file.read())

Hello! welcome to the new file


In [22]:
file = open("demo1.txt", mode= "w")
file.write("I have deleted")
file.close


<function TextIOWrapper.close()>

In [23]:
file = open("demo1.txt", mode="r")
data = file.read()
file.close()
data

''

In [18]:
file = open("demo1.txt", mode="a")
file.write("\nSecond Line")
file.writelines(["\nPython", "\nJava", "\nC#"])
file.close()



In [19]:
file = open("demo1.txt", mode="r")
data = file.readlines()
file.close()
data

['I have deleted\n',
 'This is first line\n',
 'this is the secod one\n',
 'This is first line\n',
 'This is first line\n',
 'This is first line\n',
 'This is first line\n',
 ' third\n',
 'fourth\n',
 'fifth\n',
 'This is first line\n',
 'This is first line\n',
 ' third\n',
 'fourth\n',
 'fifth\n',
 'This is first line\n',
 ' third\n',
 'fourth\n',
 'fifth\n',
 'Second Line\n',
 'Python\n',
 'Java\n',
 'C#']

In [24]:
file1 = open("demo2.txt", mode= "w")
file1.write("the first line")
file1.close()

In [25]:
file1 = open("demo2.txt" , mode= "r")
data = file1.read()
file1.close()
data

'the first line'

In [27]:
file1 = open("demo2.txt" , mode= "a")
file1.write("\nThis is second")
file1.writelines(["\nThird", "\nFourth", "\nFifth"])
file1.close()

In [28]:
file1 = open("demo2.txt" , mode= "r")
data = file1.readlines()
file1.close()
data

['the first line\n',
 'This is second\n',
 'This is second\n',
 'Third\n',
 'Fourth\n',
 'Fifth']

In [29]:
with open("demo2.txt", mode= "r") as file:
    data = file.readlines()
data



['the first line\n',
 'This is second\n',
 'This is second\n',
 'Third\n',
 'Fourth\n',
 'Fifth']

In [31]:
with open("demo2.txt", mode= "r") as file:
    lines = file.readlines()
    del lines[2]
with open("demo3.txt ", mode="w") as file:
    data = file.writelines(lines)
    file.close()
data


In [32]:
try:
    with open("file4.txt", mode = "r") as file:
        data = file.readlines()
except FileNotFoundError as e:
    print(e)
print("Hello")

[Errno 2] No such file or directory: 'file4.txt'
Hello


In [ ]:
try:
    with open("file4.txt", mode="r") as file:
        file.read()
except Exception as e:
    print(e)
finally:
    file.close()
    print("Hello0")
print("Done")


In [4]:
try:
    nominator = int(input("Enter the number :"))
    denominator = int(input("Enter the number :"))
    result = nominator / denominator
    print(result)
except Exception as e:
    print(e)
finally:
    print("Please print this out")

5.0
Please print this out


In [5]:
try:
    with open("file5.txt" , "r") as file:
        file.read()
except Exception as f:
    print(f)
finally:
    print("This should be executed")

[Errno 2] No such file or directory: 'file5.txt'


In [3]:

pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\user\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [ ]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

In [1]:
import os
current_dir = os.getcwd()
print(current_dir)

os.chdir("c:\\Users\\user\\OneDrive")
print(os.getcwd())

c:\Users\user\OneDrive\Documents
c:\Users\user\OneDrive


In [10]:
import os
print(os.listdir())

['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'Custom Office Templates', 'demo1.txt', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'New folder', 'online_banking.py', 'online_Banking_solution.py', 'online_module-based_banking.py', 'oops.ipynb', 'options_select.py', 'pass.py', 'PIN_change_options.py', 'Python Professional Training.pdf', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'transaction.py', 'Zoom', '__pycache__']


In [14]:
import os
print(os.listdir())


['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'Custom Office Templates', 'demo1.txt', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'New folder', 'online_banking.py', 'online_Banking_solution.py', 'online_module-based_banking.py', 'oops.ipynb', 'options_select.py', 'pass.py', 'PIN_change_options.py', 'Python Professional Training.pdf', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'test', 'transaction.py', 'Zoom', '__pycache__']


In [18]:
import os
os.mkdir("New folder\\test")

In [23]:
import os
print(os.listdir())

['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'Custom Office Templates', 'demo1.txt', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'New folder', 'online_banking.py', 'online_Banking_solution.py', 'online_module-based_banking.py', 'oops.ipynb', 'options_select.py', 'pass.py', 'PIN_change_options.py', 'Python Professional Training.pdf', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'test_new', 'transaction.py', 'Zoom', '__pycache__']


In [24]:
os.remove("demo1.txt")
print(os.listdir())

['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'Custom Office Templates', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'New folder', 'online_banking.py', 'online_Banking_solution.py', 'online_module-based_banking.py', 'oops.ipynb', 'options_select.py', 'pass.py', 'PIN_change_options.py', 'Python Professional Training.pdf', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'test_new', 'transaction.py', 'Zoom', '__pycache__']


In [25]:
os.rmdir("test_new")
print(os.listdir())

['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'Custom Office Templates', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'New folder', 'online_banking.py', 'online_Banking_solution.py', 'online_module-based_banking.py', 'oops.ipynb', 'options_select.py', 'pass.py', 'PIN_change_options.py', 'Python Professional Training.pdf', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'transaction.py', 'Zoom', '__pycache__']


In [26]:
import os
print(os.getcwd())

c:\Users\user\OneDrive\Documents


In [33]:
import os
os.chdir("c:\\Users\\user\\OneDrive\\Desktop")
print(os.getcwd())
print(os.listdir())

c:\Users\user\OneDrive\Desktop
['desktop.ini', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.lnk']


In [41]:
os.mkdir("imo")
#print(os.getcwd())
#print(os.listdir())
os.makedirs("imo1\\sub-dir")
print(os.listdir())




['desktop.ini', 'imo', 'imo1', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.lnk']


In [42]:
#os.rmdir("imo")
print(os.listdir())

['desktop.ini', 'imo1', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.lnk']


In [43]:
os.removedirs("imo1\\sub-dir")
print(os.listdir())

['desktop.ini', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.lnk']


In [44]:
os.rename("Zoom.lnk", "Zoom.link")
print(os.listdir())

['desktop.ini', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.link']


In [45]:
print(os.stat("Zoom.link"))

os.stat_result(st_mode=33206, st_ino=4503599627720962, st_dev=2928784602, st_nlink=1, st_uid=0, st_gid=0, st_size=1934, st_atime=1627882620, st_mtime=1625493924, st_ctime=1625493924)


In [47]:
print(os.stat("Zoom.link").st_size)
print(os.stat("Zoom.link").st_mtime)

1934
1625493924.687096


In [48]:
import os
from datetime import datetime
modification_time = os.stat("Zoom.link").st_mtime
print(datetime.fromtimestamp(modification_time))

2021-07-05 20:05:24.687096


In [52]:
import os
from datetime import datetime

for dirpath, dirnames, filenames in os.walk("c:\\Users\\user\\OneDrive\\"):
    print("Current Path :", dirpath)
    print("Directories :", dirnames)
    print("Files :",filenames)
    print()


Current Path : c:\Users\user\OneDrive\
Directories : ['Desktop', 'Documents', 'Pictures']
Files : ['.849C9593-D756-4E56-8D6E-42412F2A707B', 'desktop.ini', 'Getting started with OneDrive.pdf', 'Personal Vault.lnk']

Current Path : c:\Users\user\OneDrive\Desktop
Directories : []
Files : ['desktop.ini', 'PDF Reader for Windows 10.lnk', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'Zoom.link']

Current Path : c:\Users\user\OneDrive\Documents
Directories : ['Custom Office Templates', 'New folder', 'SIMPLE_BANKING_SYSTEM_IN_PYTHON_WITH_SOURCE_CODE', 'Zoom', '__pycache__']
Files : ['account_creation.py', 'ayushe.py', 'Ayushi2.py', 'bank.py', 'bank1.py', 'bank2.py', 'banking.py', 'card_apply.py', 'demo2.txt', 'demo3.txt', 'demofile.txt', 'desktop.ini', 'Django and Flask uses in Python.pdf', 'exercises.ipynb', 'exercises.py', 'exit.py', 'exrcises.ipynb', 'hw1.py', 'hw2.py', 'hw4.py', 'init.ipynb', 'init1.ipynb', 'main_function.py', 'online_banking.py', 'online_Banking_solution.py', 'online_module-

In [56]:
print(os.environ.get('Home'))

None


In [57]:
os.getcwd()

'c:\\Users\\user\\OneDrive\\Desktop'

In [61]:
file_path = os.path.join('c:\\Users\\user\\OneDrive\\Desktop', 'test.txt')
print(file_path)
with open(file_path, 'w') as f:
    f.write("Hello")
    #close(file_path)

c:\Users\user\OneDrive\Desktop\test.txt


In [62]:
os.path.basename("\\tmp\\test,txt")

'test,txt'

In [63]:
os.path.dirname("\\tmp\\test,txt")

'\\tmp'

In [64]:
os.path.split("\\tmp\\test,txt")

('\\tmp', 'test,txt')

In [66]:
os.path.exists("\\tmp\\test,txt")

False

In [67]:
os.path.isdir("\\tmp\\test,txt")

False

In [ ]:
os.path.isfile("\\tmp\\test,txt")

In [4]:
import time

while_count = time.time()
k = 0
while k < 10:
    print("This is time module")
    k += 1
print("While loop took", time.time() - while_count ,"seconds")

for_count = time.time()
for i in range (10):
    print("Time module in for loop")
print("For loop took", time.time() - for_count , "seconds")


This is time module
This is time module
This is time module
This is time module
This is time module
This is time module
This is time module
This is time module
This is time module
This is time module
While loop took 0.0020034313201904297 seconds
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
Time module in for loop
For loop took 0.0010023117065429688 seconds


In [2]:
import numpy as np

In [1]:
local_time = time.asctime(time.localtime(time.time()))
print(local_time)

NameError: name 'time' is not defined

In [3]:
arr = np.array([1,2,3,4,5])
arr.sum()

15

In [4]:
arr.mean()

3.0

In [5]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
%%time
res = []
for num in range(1,10000):
    res.append(num**2)
sum(res)


Wall time: 11 ms


333283335000

In [4]:
%%time
arr = np.arange(1,10000)
arr.sum()

Wall time: 0 ns


49995000

In [5]:
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.empty([3,3]) #it takes garbage value

array([[0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 6.76e-321],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [10]:
np.eye(3) #identical

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.ones([10,10,10]).ndim #dimensions

3

In [12]:
np.ones([10,10,10]).shape

(10, 10, 10)

In [14]:
np.ones([10,10,10], dtype = np.int64).dtype
dtype('int64')

NameError: name 'dtype' is not defined

In [15]:
np.ones([10,10,10]).astype(np.int64).dtype
dtype('int64')

NameError: name 'dtype' is not defined

In [16]:
arr = np.array([1,2,3,4,5,6,7])
arr[1:6]

array([2, 3, 4, 5, 6])

In [1]:
arr = np.array([
               [1,2,3,4,5,6],
               [2,3,4,5,6,7],
               [3,6,7,8,9,8]])
arr.shape

NameError: name 'np' is not defined

In [18]:
# to get the values
arr[0,1]  #first row is 0 and first colum is 0

2

In [19]:
arr[:, 1]   #first row 

array([2, 3, 6])

In [20]:
arr[1: , 3] #first row will b deducted

array([5, 8])

In [21]:
arr[1, :]

array([2, 3, 4, 5, 6, 7])

In [22]:
name = "Bob"
arr[(name == "Bob"),2:]

array([[[3, 6, 7, 8, 9, 8]]])

In [23]:
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 6, 7, 8, 9, 8]])

In [24]:
arr[: ,1] = [5,6,7]
arr

array([[1, 5, 3, 4, 5, 6],
       [2, 6, 4, 5, 6, 7],
       [3, 7, 7, 8, 9, 8]])

In [25]:
arr[2,3] = 9
arr

array([[1, 5, 3, 4, 5, 6],
       [2, 6, 4, 5, 6, 7],
       [3, 7, 7, 9, 9, 8]])

In [26]:
arr.transpose() #or arr.T()

array([[1, 2, 3],
       [5, 6, 7],
       [3, 4, 7],
       [4, 5, 9],
       [5, 6, 9],
       [6, 7, 8]])

In [27]:
np.sqrt(arr)

array([[1.        , 2.23606798, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [1.41421356, 2.44948974, 2.        , 2.23606798, 2.44948974,
        2.64575131],
       [1.73205081, 2.64575131, 2.64575131, 3.        , 3.        ,
        2.82842712]])

In [28]:
np.std(arr) #deviation

2.214570158666083

In [29]:
arr.max()

9

In [31]:
arr = np.array([2,6,4,8,5,9,1]) #it will show the index of the maximum number
arr.argmax()

5

In [32]:
arr > 3

array([False,  True,  True,  True,  True,  True, False])

In [33]:
arr[arr >= 3]

array([6, 4, 8, 5, 9])

In [34]:
arr.sort()
arr

array([1, 2, 4, 5, 6, 8, 9])

In [37]:
np.random.normal(size=(4,4))

array([[-1.10632693, -0.46307266,  0.64526393, -1.75160417],
       [-1.45592136, -0.52885765, -1.11928525,  0.80182712],
       [-1.46181735,  0.77126436, -0.72921652, -0.49560296],
       [-0.03624313,  0.34602083,  0.11421484,  0.76299673]])

In [35]:
np.unique(arr)

array([1, 2, 4, 5, 6, 8, 9])

In [36]:
np.in1d(arr,[4,5,6]) #to check the number in list

array([False, False,  True,  True,  True, False, False])

In [44]:

np.random.shuffle(arr)
arr

array([2, 0, 5, 6, 1, 4, 3, 9, 7, 8])

In [41]:
arr.reshape(2,5)

array([[9, 3, 0, 7, 8],
       [6, 2, 1, 4, 5]])

In [42]:
arr.reshape(-1,1)

array([[9],
       [3],
       [0],
       [7],
       [8],
       [6],
       [2],
       [1],
       [4],
       [5]])

In [43]:
arr.reshape(1,-1)

TypeError: 'tuple' object is not callable