In [1]:
import numpy

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

In [3]:
import numpy as np
print(np.__version__)

1.21.1


In [2]:
import numpy as np
arr = np.array([42])
arr

array([42])

In [35]:
import numpy as np
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = np.array([42])
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
e = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

1
1
2
2
3


In [12]:
arr = np.array([1,2,3,4] , ndmin = 5)

print(arr)
print("number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
arr = np.array([1,2,3,4])
print(arr[2])

3


In [26]:
arr = np.array([
    [1,2,3,4,5,6],
    [4,5,6,8,2,3],
    [7,8,6,9,7,1]])
arr.ndim

2

In [23]:
print(arr[2,1])

8


In [28]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.ndim)
print(arr)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
arr = np.array([[[1,2,3,4,5,6],[2,3,4,5,6,7]],[[2,5,4,6,7,8],[4,5,2,3,1,9]],[[4,2,6,5,1,7],[8,4,1,2,6,7]],[[6,4,1,2,8,4],[5,6,7,1,3,4]]])  #3D
arr

array([[[1, 2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6, 7]],

       [[2, 5, 4, 6, 7, 8],
        [4, 5, 2, 3, 1, 9]],

       [[4, 2, 6, 5, 1, 7],
        [8, 4, 1, 2, 6, 7]],

       [[6, 4, 1, 2, 8, 4],
        [5, 6, 7, 1, 3, 4]]])

In [49]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[4,6,8],[6,1,3]]])
print(arr)
#print 11 of the second array
print(arr[1]) #calls the second array
print(arr[1][1]) #calls the second of the selected array
print(arr[1][1][1])
print(arr[1][1][-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  6  8]
  [ 6  1  3]]]
[[ 7  8  9]
 [10 11 12]]
[10 11 12]
11
12


In [61]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr[2:7]

array([3, 4, 5, 6])

In [56]:
arr[2:]

array([3, 4, 5, 6])

In [57]:
arr[:5]

array([1, 2, 3, 4, 5])

In [59]:
arr[-4:-1] #neg index:from end index starts -1, but excludes the last index like others

array([3, 4, 5])

In [60]:
arr = np.array([2,3,4,6,5,7,9,1])
arr[1:6:2] #start:end:step

array([3, 6, 7])

In [62]:
arr[::2] #returns every element with 2 difference

array([1, 3, 5])

In [63]:
arr = np.array([[2,3,5,6,4],[8,7,3,6,5]])
arr[1, 1:4] #print from second array from 1 to 4 indx

array([7, 3, 6])

In [66]:
arr[0:2, 3]  #from both array print 3rd index

array([6, 6])

In [69]:
arr[0:2, 1:4]

array([[3, 5, 6],
       [7, 3, 6]])

In [70]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[2:5])

[20 25 30]


In [71]:
import numpy as np
arr = np.array([2,6,4,8,5])
arr.dtype

dtype('int32')

In [73]:
arr = np.array(['banana','cherry','kola'])
arr.dtype

dtype('<U6')

In [76]:
arr = np.array([2,5,9,7], dtype = 'S')
arr


array([b'2', b'5', b'9', b'7'], dtype='|S1')

In [78]:
arr = np.array([6,1,4,7], dtype = 'i4') #array function allow a parameter in which u can define dtype
arr.dtype

dtype('int32')

In [80]:
import numpy as np
arr = np.array([1.6,5.2,9.4])

newarr = arr.astype('i') # astype() func makes a copy of the array and change it to other datatypes.it also allows a parameter
print(arr)
print(newarr.dtype)

[1.6 5.2 9.4]
int32


In [81]:
arr = np.array([2.6,5.1,9.6])
newarr = arr.astype(int)
print(arr)
print(newarr)
print(newarr.dtype)

[2.6 5.1 9.6]
[2 5 9]
int32


In [82]:
arr = np.array([2.6,4.2,8.6])
newarr = arr.astype(bool)
print(arr)
print(newarr)
print(newarr.dtype)

[2.6 4.2 8.6]
[ True  True  True]
bool


In [2]:
import numpy as np
arr = np.array([1,5,6,7,9])
newarr = arr.copy()  #copy owns the data and any changes made to the copy will not affect original array
arr[0] = 24

print(arr)
print(newarr)

[24  5  6  7  9]
[1 5 6 7 9]


In [5]:
arr = np.array([2,6,7,4,3,1,9])
newarr = arr.copy()
arr[4]= 21
print(arr)
print(newarr)

[ 2  6  7  4 21  1  9]
[2 6 7 4 3 1 9]


In [6]:
arr = np.array([5,3,1,7,4,6])
newarr = arr.view() #The view does not own the data and any changes made to the view will affect the original array
arr[0] = 89
print(arr)
print(newarr)

[89  3  1  7  4  6]
[89  3  1  7  4  6]


In [7]:
arr = np.array([5,3,1,2,9,7])
x = arr.copy()  # copy owns the data. numpy has attribute 'base' which returns 'none' if it owns the data
y = arr.view()  # view doesntown the data . so 'base' returns the original data

print(x.base)
print(y.base)

None
[5 3 1 2 9 7]


In [9]:
** arr = np.array([2,6,7,80], ndmin= 5) 
print(arr)  # ndmin defines the dimensions and shape represents dimensions & elements
print(arr.shape)


[[[[[ 2  6  7 80]]]]]
(1, 1, 1, 1, 4)


In [11]:
arr = np.array([6,2,7,3,4], ndmin= 6)
print(arr)
print(arr.shape)

[[[[[[6 2 7 3 4]]]]]]
(1, 1, 1, 1, 1, 5)


In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4) # or (4,3) reshape from 1-D to 2-D
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12]])
newarr = arr.reshape(-1) # -1 makes 2-d into 1D
print(newarr)

[list([1, 2, 3, 4, 5, 6, 7]) list([8, 9, 10, 11, 12])]


C:\Users\user\AppData\Local\Temp/ipykernel_5808/1836131191.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12]])


In [3]:
arr = np.array([1,3,5,7,6,9,4,3,45,4,65,21])
newarr = arr.reshape(3,2,2) #The outermost dimension will have 3 arrays that contains 2 arrays, each with 2 elements:
newarr


array([[[ 1,  3],
        [ 5,  7]],

       [[ 6,  9],
        [ 4,  3]],

       [[45,  4],
        [65, 21]]])

In [20]:
arr = np.array([1,3,5,7,6,9,4,3,45,4,65,21])
newarr = arr.reshape(2,6)
newarr

array([[ 1,  3,  5,  7,  6,  9],
       [ 4,  3, 45,  4, 65, 21]])

In [22]:
newarr = arr.reshape(6,2)
newarr

array([ 1,  3,  5,  7,  6,  9,  4,  3, 45,  4, 65, 21])

In [9]:
arr = np.array([1,3,5,7,6,9,4,3,45,4,65,21,41,25])
newarr = arr.reshape(3,2,-1)
newarr

ValueError: cannot reshape array of size 14 into shape (3,2,newaxis)

In [5]:
arr = np.array([1,3,5,7,6,9,4,3,45,4,65,21,41,25,64,29])
newarr = arr.reshape(4,2,2)
newarr

array([[[ 1,  3],
        [ 5,  7]],

       [[ 6,  9],
        [ 4,  3]],

       [[45,  4],
        [65, 21]],

       [[41, 25],
        [64, 29]]])

In [7]:
arr = np.array([1,3,5,7,6,9,4,3,45,4,65,21,41,25,56,75])
newarr = arr.reshape(2,8) #The example above returns the original array, so it is a view but why didnt show 2D?
print(newarr.base)

[ 1  3  5  7  6  9  4  3 45  4 65 21 41 25 56 75]


In [11]:
import numpy as np
arr = np.array([2,6,7,9,14,6,59,32])
newarr = arr.reshape(2,-1,2) # when u dont know any one dimensions, use(-1)
newarr


array([[[ 2,  6],
        [ 7,  9]],

       [[14,  6],
        [59, 32]]])

In [12]:
arr = np.array([[1,2,3],[8,9,7]])
newarr = arr.reshape(-1) # to convert multidimensional array into 1D array, use -1
newarr

array([1, 2, 3, 8, 9, 7])

In [13]:
arr = np.array([2,6,7,4])
for x in arr: #iteration
    print(x)

2
6
7
4


In [14]:
arr = np.array([[1,6,7],[6,4,2]])
for x in arr:  # it will show the values in rows
    print(x)

[1 6 7]
[6 4 2]


In [16]:
arr = np.array([[1,6,7],[6,4,2]])
for x in arr:  #To return the actual values, the scalars, we have to iterate the arrays in each dimension 
 for y in x:
        print(y)

1
6
7
6
4
2


In [19]:
arr = np.array([[[1,2,3],[4,6,8]],[[5,9,7],[6,4,7]]])
for x in arr:
    print("x represents 2D array")
    print(x)

x represents 2D array
[[1 2 3]
 [4 6 8]]
[1 2 3]
[4 6 8]
x represents 2D array
[[5 9 7]
 [6 4 7]]
[5 9 7]
[6 4 7]


In [21]:
arr = np.array([[[1,2,3],[4,6,8]],[[5,9,7],[6,4,7]]])
for x in arr: # getting the scalar values in 3d array
    for y in x:
        for z in y:
            print(z)

1
2
3
4
6
8
5
9
7
6
4
7


In [22]:
arr = np.array([[[1,2,3],[4,6,8]],[[5,9,7],[6,4,7]]])
for x in np.nditer(arr):  # nditer eases the function used by for loops for iteration to get scalar elements
    print(x)

1
2
3
4
6
8
5
9
7
6
4
7


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])  #to join the two array, use concatenate  for 1D array

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [6]:
arr1 = np.array([[1,2,3],[6,5,8]])
arr2 = np.array([[5,4,7],[6,7,1]])
arr = np.concatenate((arr1,arr2), axis = 1) # joining for 2D array
arr

array([[1, 2, 3, 5, 4, 7],
       [6, 5, 8, 6, 7, 1]])

In [9]:
import numpy as np
arr1 = np.array([2,5,6])    #stacking is same as concatenation but has some other functions as well
arr2 = np.array([6,7,3])
arr = np.stack((arr1,arr2), axis= 1) #stacking is done along a new axis 
arr

array([[2, 6],
       [5, 7],
       [6, 3]])

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([6,5,8])
arr = np.hstack((arr1,arr2))  #stacking by rows
arr

array([1, 2, 3, 6, 5, 8])

In [11]:
arr1 = np.array([1,5,3])
arr2 = np.array([5,8,9])
arr = np.vstack((arr1,arr2))  #stacking by column (vertical)
arr

array([[1, 5, 3],
       [5, 8, 9]])

In [12]:
arr1 = np.array([5,9,3])
arr2 = np.array([9,3,4])
arr = np.dstack((arr1,arr2)) # stacking by depth
arr

array([[[5, 9],
        [9, 3],
        [3, 4]]])

In [19]:
arr1 = np.array([1,6,4,8,7,3,5,6])
arr = np.array_split(arr1, 3)  # splitting the array into the split number u want
print(arr)
arr[1]

[array([1, 6, 4]), array([8, 7, 3]), array([5, 6])]


array([8, 7, 3])

In [15]:
arr = np.array_split(arr1, 5)
arr

[array([1, 6]), array([4, 8]), array([7, 3]), array([5]), array([6])]

In [20]:
arr = np.array([[1,2,6],[5,4,6],[9,6,4],[3,7,6]])
newarr = np.array_split(arr, 3)
newarr

[array([[1, 2, 6],
        [5, 4, 6]]),
 array([[9, 6, 4]]),
 array([[3, 7, 6]])]

In [21]:
arr = np.array([[1,2,6],[5,4,6],[9,6,4],[3,7,6]])
newarr = np.hsplit(arr, 3)
newarr

[array([[1],
        [5],
        [9],
        [3]]),
 array([[2],
        [4],
        [6],
        [7]]),
 array([[6],
        [6],
        [4],
        [6]])]

In [23]:
arr = np.array([
               [1,2,3,4,5,6],
               [2,3,4,5,6,7],
               [3,6,7,8,9,8]])
rr.shape

(3, 6)

In [25]:
arr[:, 2]  #first row and 3rd colum selected

array([3, 4, 7])

In [26]:
arr[1:, 4] #1st row is deducted

array([6, 9])

In [27]:
arr[1,:]

array([2, 3, 4, 5, 6, 7])

In [28]:
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 6, 7, 8, 9, 8]])

In [29]:
arr[:,1] = [9,2,6]
arr

array([[1, 9, 3, 4, 5, 6],
       [2, 2, 4, 5, 6, 7],
       [3, 6, 7, 8, 9, 8]])

In [31]:
arr[:, 0] = [2,3,4,5,6,7]
arr

ValueError: could not broadcast input array from shape (6,) into shape (3,)